# Generated by Django 3.2.5 on 2021-07-29 07:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rssfeeditem',
            name='text',
        ),
        migrations.AddField(
            model_name='rssfeeditem',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
