# Generated by Django 3.2.5 on 2021-07-29 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0002_auto_20210729_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeeditem',
            name='feed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rss.rssfeed'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rssfeeditem',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
